### ISSUE TITLE
How to realise to use full-length reads in the first round of clustering?

### ISSUE THREAD

**Issue by qhli1** [Runsheng/trackcluster#2]
You provide two parameters, ratio and ratio short when computing the similarity score. But I do not find that your programs can automatically identify full-length reads and use those reads to finish the first round of clustering. 
Therefore, I want to ask how to just use full-length reads to cluster them in advance?

**Comment by Runsheng** [comment]
Dear Qh,

Sorry, I was away from the internet and will be away from the internet for the next several weeks. The full-length tracks can be manually marked before feeding into the trackcluster pipeline. The most convenient way is to give a high "full-length" score (>=20). 

For the _C. elegans_ reads, the full-length score was calculated using the probability of the presence of the splicing leader signal; while for the libraries with 5' adaptors, the score can be also be calculated by the probability of the presence of the adaptor sequence. 
BTW, the score is the 5th column of a bigGenPred track. 

Best regards,
Runsheng

**Comment by qhli1** [comment]
Hi, Thanks for ur explanations. In your supplementary file, you mention the similarity score2 is to merge the tracks from partial-length long reads with the one defined by a full-length read. So, in the first round, do we need to compute the score 2 when only using fully-length reads?
