### ISSUE TITLE
How can I use the trackcluster for the Arabidopsis code?

### ISSUE THREAD

**Issue by swZhang1** [Runsheng/trackcluster#3]
Dear Dr. Runsheng, 
    I've read about ur paper concerning the devising of trackcluster in C. elegants, and interested in further using it for denovo isoform identification in higher plants(e.g. Arabidopsis thaliana Col-0). What the detailed workflow(Preferably with a tutorial of commandline code) of trackcluster installation&usage? I'm a greenhand in BioInfo^^. Looking forward to ur reply.

Zhangsw, 20200909.

**Comment by Runsheng** [comment]
Sorry I missed your issue. I moved to a new position and sometimes have a limited internet connection. 
There is a brief walkthrough described in the [ipython notebook](https://github.com/Runsheng/trackcluster/blob/master/trackcluster_run_example.ipynb). I am working on a general wrapper for a simple cmd run. This branch would be tested and released next month. 

Regards,
Runsheng

**Comment by swZhang1** [comment]
Haha,sorry to overlook the walkthrough documentation. Actually i noticed the notebook file later.

I've been studying these days on the excellent tool u developed and released, and very happy to get your reply.  













At 2020-09-12 22:13:53, "Runsheng" <notifications@github.com> wrote:

Sorry I missed your issue. I moved to a new position and sometimes have a limited internet connection.
There is a brief walkthrough described in the ipython notebook. I am working on a general wrapper for a simple cmd run. This branch would be tested and released next month.

Regards,
Runsheng
